try:
    10/0
except Exception as e:
    print(f'ocurrio un error: {e}')

    